# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vanilla_browser_dialog_editsessions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditSessions(object):
    def setupUi(self, EditSessions):
        EditSessions.setObjectName("EditSessions")
        EditSessions.resize(352, 212)
        self.list_sessions = QtWidgets.QListWidget(EditSessions)
        self.list_sessions.setGeometry(QtCore.QRect(10, 10, 231, 192))
        self.list_sessions.setObjectName("list_sessions")
        self.push_add = QtWidgets.QPushButton(EditSessions)
        self.push_add.setGeometry(QtCore.QRect(260, 10, 75, 31))
        self.push_add.setObjectName("push_add")
        self.push_edit = QtWidgets.QPushButton(EditSessions)
        self.push_edit.setGeometry(QtCore.QRect(260, 50, 75, 31))
        self.push_edit.setObjectName("push_edit")
        self.push_delete = QtWidgets.QPushButton(EditSessions)
        self.push_delete.setGeometry(QtCore.QRect(260, 90, 75, 31))
        self.push_delete.setObjectName("push_delete")
        self.pushClose = QtWidgets.QPushButton(EditSessions)
        self.pushClose.setGeometry(QtCore.QRect(260, 180, 75, 23))
        self.pushClose.setObjectName("pushClose")

        self.retranslateUi(EditSessions)
        QtCore.QMetaObject.connectSlotsByName(EditSessions)

    def retranslateUi(self, EditSessions):
        _translate = QtCore.QCoreApplication.translate
        EditSessions.setWindowTitle(_translate("EditSessions", "Modifier les sessions"))
        self.push_add.setText(_translate("EditSessions", "Ajouter"))
        self.push_edit.setText(_translate("EditSessions", "Modifier"))
        self.push_delete.setText(_translate("EditSessions", "Supprimer"))
        self.pushClose.setText(_translate("EditSessions", "Fermer"))
