# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vanilla_browser_dialog_layers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseLayer(object):
    def setupUi(self, ChooseLayer):
        ChooseLayer.setObjectName("ChooseLayer")
        ChooseLayer.resize(400, 300)
        self.list_layers = QtWidgets.QListWidget(ChooseLayer)
        self.list_layers.setGeometry(QtCore.QRect(70, 40, 256, 192))
        self.list_layers.setObjectName("list_layers")
        self.push_confirm = QtWidgets.QPushButton(ChooseLayer)
        self.push_confirm.setGeometry(QtCore.QRect(240, 260, 75, 23))
        self.push_confirm.setObjectName("push_confirm")
        self.push_cancel = QtWidgets.QPushButton(ChooseLayer)
        self.push_cancel.setGeometry(QtCore.QRect(320, 260, 75, 23))
        self.push_cancel.setObjectName("push_cancel")

        self.retranslateUi(ChooseLayer)
        QtCore.QMetaObject.connectSlotsByName(ChooseLayer)

    def retranslateUi(self, ChooseLayer):
        _translate = QtCore.QCoreApplication.translate
        ChooseLayer.setWindowTitle(_translate("ChooseLayer", "Choisir une couche"))
        self.push_confirm.setText(_translate("ChooseLayer", "Choisir"))
        self.push_cancel.setText(_translate("ChooseLayer", "Annuler"))
