# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vanilla_browser_dialog_createsession.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateSession(object):
    def setupUi(self, CreateSession):
        CreateSession.setObjectName("CreateSession")
        CreateSession.resize(342, 300)
        self.line_Name = QtWidgets.QLineEdit(CreateSession)
        self.line_Name.setGeometry(QtCore.QRect(60, 50, 221, 20))
        self.line_Name.setObjectName("line_Name")
        self.line_URL = QtWidgets.QLineEdit(CreateSession)
        self.line_URL.setGeometry(QtCore.QRect(60, 100, 221, 20))
        self.line_URL.setObjectName("line_URL")
        self.line_User = QtWidgets.QLineEdit(CreateSession)
        self.line_User.setGeometry(QtCore.QRect(60, 150, 221, 20))
        self.line_User.setObjectName("line_User")
        self.line_Pwd = QtWidgets.QLineEdit(CreateSession)
        self.line_Pwd.setGeometry(QtCore.QRect(60, 200, 221, 20))
        self.line_Pwd.setObjectName("line_Pwd")
        self.line_Pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_SessionName = QtWidgets.QLabel(CreateSession)
        self.label_SessionName.setGeometry(QtCore.QRect(60, 30, 121, 16))
        self.label_SessionName.setObjectName("label_SessionName")
        self.label_Mdp = QtWidgets.QLabel(CreateSession)
        self.label_Mdp.setGeometry(QtCore.QRect(60, 180, 81, 16))
        self.label_Mdp.setObjectName("label_Mdp")
        self.label_URL = QtWidgets.QLabel(CreateSession)
        self.label_URL.setGeometry(QtCore.QRect(60, 80, 221, 16))
        self.label_URL.setObjectName("label_URL")
        self.label_User = QtWidgets.QLabel(CreateSession)
        self.label_User.setGeometry(QtCore.QRect(60, 130, 121, 16))
        self.label_User.setObjectName("label_User")
        self.push_Confirm = QtWidgets.QPushButton(CreateSession)
        self.push_Confirm.setGeometry(QtCore.QRect(180, 260, 75, 23))
        self.push_Confirm.setObjectName("push_Confirm")
        self.pushClose = QtWidgets.QPushButton(CreateSession)
        self.pushClose.setGeometry(QtCore.QRect(260, 260, 75, 23))
        self.pushClose.setObjectName("pushClose")

        self.retranslateUi(CreateSession)
        QtCore.QMetaObject.connectSlotsByName(CreateSession)

    def retranslateUi(self, CreateSession):
        _translate = QtCore.QCoreApplication.translate
        CreateSession.setWindowTitle(_translate("CreateSession", "Session"))
        self.label_SessionName.setText(_translate("CreateSession", "Nom de la session :"))
        self.label_Mdp.setText(_translate("CreateSession", "Mot de passe :"))
        self.label_URL.setText(_translate("CreateSession", "URL Vanilla :"))
        self.label_User.setText(_translate("CreateSession", "Utilisateur :"))
        self.push_Confirm.setText(_translate("CreateSession", "Valider"))
        self.pushClose.setText(_translate("CreateSession", "Annuler"))
