# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vanilla_browser_dialog_createcontract.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createContract(object):
    def setupUi(self, createContract):
        createContract.setObjectName("createContract")
        createContract.resize(382, 428)
        self.line_contractName = QtWidgets.QLineEdit(createContract)
        self.line_contractName.setGeometry(QtCore.QRect(40, 40, 301, 20))
        self.line_contractName.setObjectName("line_contractName")
        self.line_externalSource = QtWidgets.QLineEdit(createContract)
        self.line_externalSource.setGeometry(QtCore.QRect(40, 90, 301, 20))
        self.line_externalSource.setObjectName("line_externalSource")
        self.line_externalId = QtWidgets.QLineEdit(createContract)
        self.line_externalId.setGeometry(QtCore.QRect(40, 140, 301, 20))
        self.line_externalId.setObjectName("line_externalId")
        self.combo_supplier = QtWidgets.QComboBox(createContract)
        self.combo_supplier.setGeometry(QtCore.QRect(40, 190, 301, 22))
        self.combo_supplier.setObjectName("combo_supplier")
        self.label = QtWidgets.QLabel(createContract)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(createContract)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(createContract)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(createContract)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 91, 16))
        self.label_4.setObjectName("label_4")
        self.push_createContract = QtWidgets.QPushButton(createContract)
        self.push_createContract.setGeometry(QtCore.QRect(210, 400, 75, 23))
        self.push_createContract.setObjectName("push_createContract")
        self.pushClose = QtWidgets.QPushButton(createContract)
        self.pushClose.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.pushClose.setObjectName("pushClose")
        self.label_5 = QtWidgets.QLabel(createContract)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 121, 16))
        self.label_5.setObjectName("label_5")
        self.combo_selectedLayer = QtWidgets.QComboBox(createContract)
        self.combo_selectedLayer.setGeometry(QtCore.QRect(40, 280, 301, 22))
        self.combo_selectedLayer.setObjectName("combo_selectedLayer")

        self.retranslateUi(createContract)
        QtCore.QMetaObject.connectSlotsByName(createContract)

    def retranslateUi(self, createContract):
        _translate = QtCore.QCoreApplication.translate
        createContract.setWindowTitle(_translate("createContract", "Créer un contrat"))
        self.label.setText(_translate("createContract", "Nom du contrat :"))
        self.label_2.setText(_translate("createContract", "Source externe :"))
        self.label_3.setText(_translate("createContract", "Identifiant externe : "))
        self.label_4.setText(_translate("createContract", "Fournisseur :"))
        self.push_createContract.setText(_translate("createContract", "Créer"))
        self.pushClose.setText(_translate("createContract", "Annuler"))
        self.label_5.setText(_translate("createContract", "Ajouter une couche :"))
