# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vanilla_browser_dialog_logins.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject

class LoginsWindow(QObject):
        loginsEntered = QtCore.pyqtSignal(str, str, str)

class Ui_LoginWindow(object):
    
    def __init__(self):
        
        self.logins_window = LoginsWindow()

    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(383, 389)
        self.lineURL = QtWidgets.QLineEdit(LoginWindow)
        self.lineURL.setGeometry(QtCore.QRect(80, 170, 221, 20))
        self.lineURL.setObjectName("lineURL")
        self.lineUser = QtWidgets.QLineEdit(LoginWindow)
        self.lineUser.setGeometry(QtCore.QRect(80, 210, 221, 20))
        self.lineUser.setObjectName("lineUser")
        self.linePassword = QtWidgets.QLineEdit(LoginWindow)
        self.linePassword.setGeometry(QtCore.QRect(80, 250, 221, 20))
        self.linePassword.setObjectName("linePassword")
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)

        self.label_URL = QtWidgets.QLabel(LoginWindow)
        self.label_URL.setGeometry(QtCore.QRect(80, 150, 47, 13))
        self.label_URL.setObjectName("label_URL")
        self.label_User = QtWidgets.QLabel(LoginWindow)
        self.label_User.setGeometry(QtCore.QRect(80, 190, 61, 16))
        self.label_User.setObjectName("label_User")
        self.label_Password = QtWidgets.QLabel(LoginWindow)
        self.label_Password.setGeometry(QtCore.QRect(80, 230, 81, 16))
        self.label_Password.setObjectName("label_Password")
        self.push_connection = QtWidgets.QPushButton(LoginWindow)
        self.push_connection.setGeometry(QtCore.QRect(214, 352, 81, 31))
        self.push_connection.setObjectName("push_connection")
        self.push_close = QtWidgets.QPushButton(LoginWindow)
        self.push_close.setGeometry(QtCore.QRect(300, 352, 81, 31))
        self.push_close.setObjectName("push_close")
        self.label_error = QtWidgets.QLabel(LoginWindow)
        self.label_error.setGeometry(QtCore.QRect(80, 280, 221, 16))
        self.label_error.setObjectName("label_error")
        self.comboBox_sessions = QtWidgets.QComboBox(LoginWindow)
        self.comboBox_sessions.setGeometry(QtCore.QRect(80, 80, 221, 22))
        self.comboBox_sessions.setObjectName("comboBox_sessions")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(80, 60, 101, 16))
        self.label.setObjectName("label")
        self.push_editSessions = QtWidgets.QPushButton(LoginWindow)
        self.push_editSessions.setGeometry(QtCore.QRect(204, 110, 101, 23))
        self.push_editSessions.setObjectName("push_editSessions")

        self.push_connection.clicked.connect(self.getLogins)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Connexion"))
        self.label_URL.setText(_translate("LoginWindow", "URL :"))
        self.label_User.setText(_translate("LoginWindow", "Utilisateur :"))
        self.label_Password.setText(_translate("LoginWindow", "Mot de Passe :"))
        self.push_connection.setText(_translate("LoginWindow", "Se connecter"))
        self.push_close.setText(_translate("LoginWindow", "Annuler"))
        self.label_error.setText(_translate("LoginWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("LoginWindow", "Session enregistrés :"))
        self.push_editSessions.setText(_translate("LoginWindow", "Gérer les sessions"))

    def getLogins(self):
        url = self.lineURL.text()
        login = self.lineUser.text()
        password = self.linePassword.text()
        self.logins_window.loginsEntered.emit(url, login, password)